[package]
name = "project-rts"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.17", default-features = true, features = [
  "bevy_asset","bevy_audio","bevy_pbr","bevy_sprite","bevy_text","bevy_ui","bevy_winit","png","x11"
] }

[profile.release]
lto = "thin"
codegen-units = 1
